[package]
name = "wows-replays"
version = "0.1.0"
authors = ["Lane Kolbly <lane@rscheme.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "6.0.0-alpha1"
hexdump = "0.1.0"
flate2 = "1.0.14"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
thiserror = "1.0.19"
rust-crypto = "0.2.36"
log = "0.4.11"
roxmltree = "0.14.1"
galil-seiferas = "0.1.5"
serde-pickle = "0.6.2"
plotters = "0.2.15"
image = "0.23.4"
rust-embed = "5.9.0"
modular-bitfield = "0.11.2"
